apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: jenkins-project
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myfirstapp
        image: leminepam/dockerhub:test
        ports:
        - containerPort: 8080
