apiVersion: v1
kind: Service
metadata:
  name: { { .Values.name } }-svc
    namespace: { { .Values.namespace } }
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - nodePort:
      port: 80
      targetPort: 80