apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: jenkins-project
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        command:
            - /bin/sh
            - '-c'
            - >-
              rm ./usr/share/nginx/html/index.html && echo "hello world" >>
              ./usr/share/nginx/html/index.html && service nginx start && sleep
              infinity
        image: nginx
        ports:
        - containerPort: 80
