apiVersion: v1
kind: Pod
metadata:
  name: lem-web123
  labels:
    role: websrv
spec:
  containers:
    - name: web
      image: nginx
      command:
        - /bin/sh
        - '-c'
        - >-
          rm ./usr/share/nginx/html/index.html && echo "hello world" >>
          ./usr/share/nginx/html/index.html && service nginx start && sleep
          infinity
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
