apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins-project
  name: lem-web123
  labels:
    role: websrv
spec:
  containers:
    - name: web
      image: nginx
      command:
        - echo "DONE!"
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
